### ISSUE TITLE
Project not available via Pypi - what are the plans?

### ISSUE THREAD

**Issue by cpaulik** [openearth/ddlpy#12]
HI,

There is a link in the readme that points to https://pypi.org/project/ddlpy/ which does not exist.

What are the plans of making this package available via pypi? It would make dependency management and installation in other projects somewhat easier if there would be an official package.

**Comment by isabelbrandao** [comment]
Hi cpaulik, could you install ddlpy?

**Comment by cpaulik** [comment]
Yes we were able to install it directly from the repo as far as I know. Why are you asking?

**Comment by cpaulik** [comment]
Ok, I think that might be best discussed in a separate issue. Although it does not seem that the developers of this package are very responsive...

**Comment by SiggyF** [comment]
Thanks, I have made this package available here https://pypi.org/project/rws-ddlpy/

**Comment by SiggyF** [comment]
Note that you can install the github version, after checkout, using:
`pip install -e . `

**Comment by SiggyF** [comment]
> I'm asking because I've installed it but when I use the notebooks or minimal_example.py, I get an error that ddlpy is not found.

It can find the library even if not installed if you are one directory up from the notebook directory. The notebook assumes you installed the package using `pip install -e .` from the directory containing `setup.py`. Or (since a few minutes ago) after pip install rws-ddlpy.

**Comment by cpaulik** [comment]
Thanks. That should make our lives easier. As a side note - the badge in the readme still refers to the old package name

**Comment by veenstrajelmer** [comment]
Another release of ddlpy was created today and all docs and examples were updated. Please open a new issue if you encounter any bugs.
