### ISSUE TITLE
All download are empty

### ISSUE THREAD

**Issue by julietbravo** [openearth/ddlpy#14]
* Version: `ddlpy 0.1.0` (installed through `pip`)
* Python version: `3.10.1`
* Operating System: `Linux`

### Description
As a first test of `ddlpy`, I modified `example/minimal_example.py` to download water temperatures for a number of locations with the script attached below. Whatever date/period I try, I never manage to get any data, and I have no idea what I'm doing wrong. Any ideas?

p.s.: I'm not sure if this is the best location to ask for help, please let me know if there are better alternatives...

### What I Did

```
from ddlpy import ddlpy
import datetime

if 'locations' not in locals():
    locations = ddlpy.locations()

code = 'T'
stations = ['HAGB', 'KDD50', 'BRB65', 'AMRB']

start_date = datetime.datetime(2018, 1, 1)
end_date   = datetime.datetime(2018, 2, 1)

selected = locations[locations.index.isin(stations)]
selected = selected[(selected['Grootheid.Code'] == code)].reset_index()

for i in range(len(selected)):
    location = selected.iloc[i]
    measurements = ddlpy.measurements(location, start_date=start_date, end_date=end_date)

    if len(measurements) == 0:
        print('{}: no data!'.format(location.Naam))
    else:
        print('{}: data!'.format(location.Naam))
```
Results in:

```
In [3]: run -i download_RWS.py
100%|█████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.46it/s]
Brienenoordbrug NAP-6.5 m: no data!
100%|█████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.32it/s]
Kinderdijk NAP -5m: no data!
100%|█████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  9.19it/s]
Amerongen boven: no data!
100%|█████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.62it/s]
Hagestein boven: no data!
```

**Comment by AndriesPbg** [comment]
Good morning,
I am experiencing a similar problem.
I also started from 'minimal_example.py' to download water levels for the Waal river in the Netherlands, for the period end 2019/ start 2020. Through ddlpy I get No data, while a manual download from waterinfo.rws.nl does give me data.
Any help is appriciated!

**Comment by wstolte** [comment]
Try to download data from last month. For some stations (perhaps all LMW stations?), there are versions (same location, but different locationcode) of the data in the DDL. One with data from last few months (varying), and one with archived data. If your script works to retrieve data from last month, this might be the case here. 

The reason for this is (as far as I know) that data are transferred from the LMW database to DONAR after a few months. The solution is to retrieve the data with the DONAR location code and related coordinates.

**Comment by julietbravo** [comment]
Downloading data from last month indeed works.

**Comment by AndriesPbg** [comment]
@wstolte For a more recent period, I get data.
I will try your suggestions and let you know the result. Cheers, Andries

**Comment by veenstrajelmer** [comment]
An additional method to get the other Hagestein stations (or any other), would be to use this code:
```python
import ddlpy

locations = ddlpy.locations()
bool_stations = locations['Naam'].str.contains('hagestein', case=False)
bool_grootheid = locations['Grootheid.Code'].isin(['T'])
selected = locations.loc[bool_stations & bool_grootheid]

print(selected[['Naam','Grootheid.Code']])
```

It prints:
```
                       Naam Grootheid.Code
Code                                      
HAGB        Hagestein boven              T
HAGSN             Hagestein              T
HAGSBNDN  Hagestein beneden              T
HAGSBVN     Hagestein boven              T
```

With the explanation from @wstolte I think the problem in this issue was correctly addressed, so I will now close this issue. You are free to comment if your problem is not resolved, or post a new issue.
