### ISSUE TITLE
Pip installation readme

### ISSUE THREAD

**Issue by pepijntje02** [openearth/ddlpy#16]
* Data Distributie Laag. Service from Rijkswaterstaat for distributing water quantity data. version:
* Python version: 3.9
* Operating System: Windows

### Description

Install using pip. Could not find a version that satisfies the requirement ddlpy.

```
ERROR: Could not find a version that satisfies the requirement ddlpy (from versions: none)
ERROR: No matching distribution found for ddlpy
```

### What I Did
Using pip with:
```
pip install rws-ddlpy
```
Found here: https://pypi.org/project/rws-ddlpy/. 

I would suggest to update the `readme` since there states that it is possible to install the package using 
```
pip install ddlpy
```

But I guess that it should be
```
pip install rws-ddlpy
```

I am not sure how to create a pull request to change it. Therefore i created this issue, perhaps the maintainer can add this to the `readme` if desired.

**Comment by RPNicolai** [comment]
Met onderstaande lukt het wel:

pip install git+https://github.com/openearth/ddlpy.git#egg=rws-ddlpy

Met conda is het me niet gelukt.

**Comment by veenstrajelmer** [comment]
@pepijntje02 this is indeed a good suggestion, we will fix this in the near future. Thanks for your suggestion.

**Comment by veenstrajelmer** [comment]
The readme was updated. Since the latest release does not support newer pandas versions, I recommend installing directly from git for now. We will do some maintenance first, before we create a new PyPI release. It might become available as ddlpy instead of rws-ddlpy on PyPI also.

**Comment by veenstrajelmer** [comment]
Another release of ddlpy was created today and all docs and examples were updated. Please open a new issue if you encounter any bugs.
