### ISSUE TITLE
ddlpy download hangs indefinitely when RWS servers are not available

### ISSUE THREAD

**Issue by j0nes2k** [openearth/ddlpy#19]
* Data Distributie Laag. Service from Rijkswaterstaat for distributing water quantity data. version: 0.1.0
* Python version: 3.11
* Operating System: Linux

### Description

When the [RWS servers](https://waterwebservices.rijkswaterstaat.nl/) are not responding, ddlpy hangs indefinitely. 

### What I Did

```
import ddlpy
ddlpy.locations()
```

The error obviously only occurs when the servers are not available.

### Possible solution

The corresponding [calls](https://github.com/openearth/ddlpy/blob/6c4f700c4048012fc2001a33f45d0bb0760422c9/ddlpy/ddlpy.py#L42) via requests lib should include a `timeout` parameter.

**Comment by veenstrajelmer** [comment]
Since this issue has been open for a long time without activity, I will now close it. Please re-open this issue or comment on it if you encounter the issue again, so we can test your proposed solution during downtime of the RWS servers.
