### ISSUE TITLE
GitHub vs. PyPi installation

### ISSUE THREAD

**Issue by Weidav** [openearth/ddlpy#47]
The readme was updated, so I will now close this issue. Since the latest release does not support newer pandas versions, I recommend installing directly from git for now. We will do some maintenance first, before we create a new PyPI release. It might become available as ddlpy instead of rws-ddlpy on PyPI also.

_Originally posted by @veenstrajelmer in https://github.com/openearth/ddlpy/issues/16#issuecomment-1973321555_
            
First of all, thank you for all the development that happened recently!
Will the direct installation from git stay the recommended way of installation in the near future, or are you planning to release a the new version to pypi?

**Comment by veenstrajelmer** [comment]
@Weidav we plan to do a new release soon after some addional improvements are also done. If possible, we might rename the pip-installable version from "rws-ddlpy" to "ddlpy" also, for consistency. We will update the readme as soon as a new release is available.

**Comment by veenstrajelmer** [comment]
Another release of ddlpy was created today and all docs are updated. Please open a new issue if you encounter any bugs or have suggestions
