### ISSUE TITLE
Empty dataframe line 171 in ddlpy.py

### ISSUE THREAD

**Issue by HesselVoortman** [openearth/ddlpy#7]
* Data Distributie Laag. Service from Rijkswaterstaat for distributing water quantity data. version:
* Python version: 3.8
* Operating System: Windows

### Description
Downloading data station Lobith. Dataframe "measurements" empty after removal of duplicates.
### What I Did
Line 171 in ddlpy.py reads: 
measurements = measurements.drop_duplicates(inplace = True)

Modified to:
measurements.drop_duplicates(inplace = True)

which yields the correct result and avoids the error.

**Comment by SiggyF** [comment]
Thanks for your contribution Hessel. 
It is now implemented as `measurements = measurements.drop_duplicates()` which is the same as `measurements.drop_duplicates(inplace = True)`.

**Comment by veenstrajelmer** [comment]
Another release of ddlpy was created today and all docs and examples were updated. Please open a new issue if you encounter any bugs.
